<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageProducts.aspx.cs" Inherits="Admin.ManageProducts" %>
<!DOCTYPE html>
<%@ Register Src="~/control/sidebar.ascx" TagName="Sidebar" TagPrefix="dside" %>
<%@ Register Src="~/control/header.ascx" TagName="Heading" TagPrefix="dhead" %>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Products</title>
    <link href="dashboard.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

    <script type="text/javascript">
        function showAlertForRemove(message) {
            Swal.fire({
                icon: 'success',
                title: 'Success',
                text: message,
                confirmButtonText: 'OK'
            });
        }
    </script>

</head>
<body>
    <dhead:Heading ID="header1" runat="server" />
    <div class="container-fluid"  style="margin-left:-13px">
        <dside:Sidebar ID="sidebar1" runat="server"/>
    <form id="form1" runat="server">
        <div class="text-center">
            <h1>Manage Products</h1>
          
            
    <asp:GridView ID="GridView1" runat="server"
         AutoGenerateDeleteButton="True" DataKeyNames="pid"
         CssClass="table table-striped text-center"
         OnRowDeleting="GridView1_RowDeleting"
         OnRowDataBound="GridView1_RowDataBound" CellPadding="10">
     </asp:GridView>
            <asp:Button id="btnadd" Text="ADD" class="btn cust-btn2" runat="server" OnClick="btnadd_Click" />

        </div>
    </form>
    </div>
</body>
</html>

