<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageCust.aspx.cs" Inherits="Admin.ManageCust" %>

<!DOCTYPE html>
<%@ Register Src="~/control/sidebar.ascx" TagName="Sidebar" TagPrefix="dside" %>
<%@ Register Src="~/control/header.ascx" TagName="Heading" TagPrefix="dhead" %>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Customers</title>
    <link href="dashboard.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script type="text/javascript">
        function showAlertForRemove(message) {
            Swal.fire({
                icon: 'success',
                title: 'Success',
                text: message
            });
        }
    </script>

</head>
<body>
    <dhead:Heading ID="header1" runat="server" />
    <div class="container-fluid" style="margin-left: -13px">
        <dside:Sidebar ID="sidebar1" runat="server" />
        <form id="form1" runat="server">
            <div class="text-center">

                <h1>Manage Customers</h1>
                <%--Add Content Here--%>
                <asp:GridView ID="GridView1" runat="server" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False" CssClass="table table-striped" AutoGenerateDeleteButton="True" DataKeyNames="CustomerID" CellPadding="120" CellSpacing="10">
                    <Columns>
                        <asp:BoundField DataField="CustomerID" HeaderText="Customer ID" />
                        <asp:BoundField DataField="UserName" HeaderText="User Name" />
                        <asp:BoundField DataField="Password" HeaderText="Password" />
                        <asp:BoundField DataField="EmailID" HeaderText="Email ID" />
                        <asp:BoundField DataField="ContactNo" HeaderText="Contact Number" />
                        <asp:BoundField DataField="City" HeaderText="City" />
                        <asp:BoundField DataField="Address" HeaderText="Address" />
                    </Columns>
                </asp:GridView>
            </div>
        </form>
    </div>
</body>
</html>
